############################
## CHANGE THESE
############################

baseURL: "https://geekspeed.github.io/qubtHugoClean"
title: qubtHugoClean

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
